name: fedora

on: [push, pull_request]

jobs:

  build-container-image:

    runs-on: ubuntu-latest
    name: build-container-image

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the image
        run: docker build -f Dockerfile.fedora -t fedora:local .

      - name: Export the image
        run: docker save -o fedora-local.tar fedora:local

      - name: Upload the image
        uses: actions/upload-artifact@v4
        with:
          name: ci-images
          if-no-files-found: error
          path: fedora-local.tar
          retention-days: 1

  e2e:

    strategy:
      matrix:
        include:
          - name: e2e-all
            script: docker run fedora:local all
          - name: e2e-link
            script: docker run fedora:local link

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: [build-container-image]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download container images
        uses: actions/download-artifact@v4
        with:
          name: ci-images

      - name: Load image
        run: docker load --input fedora-local.tar

      - name: Run test
        run: ${{ matrix.script }}
