name: macOS

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:

  e2e:
    name: e2e
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        make no-packages
        make all
