name: macOS

on: [push, pull_request]

jobs:

  e2e:

    strategy:
      matrix:
        include:
          - name: e2e-all
            script: make all
          - name: e2e-link
            script: make link

    name: ${{ matrix.name }}
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run test
        run: ${{ matrix.script }}
