name: ubuntu

on: [push, pull_request]

jobs:

  e2e:

    strategy:
      matrix:
        include:
          - name: e2e-all
            script: make all
          - name: e2e-no-packages
            script: make no-packages

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run test
        run: ${{ matrix.script }}
